### PR TITLE
feat: add boilerplate

### PR DESCRIPTION
**Pull request by Innei**
## Resource type _(required)_

- [x] GitHub Repository:
    - [x] **(Required)** I confirm that the GitHub repository has more than **10 stars**.
    - [x] **(Required)** The repository is not archived.
- [ ] Video.
- [x] Tutorial.
- [ ] Meetups.
- [ ] Improve documentation _(grammatical corrections, improve doc style, ...)_.

> If your contribution is NOT a GitHub repository, then you can skip the next titles, except "Rules".

## Description _(required)_

A NestJS template, which used the coolest and fastest stuff.

## Link _(required)_

[_Paste link here._](https://github.com/Innei/nest-http-boilerplate)

## Rules _(required)_

- [x] **NestJS / Nest**: It's not nest, nestjs, nest.js, and other variants.
- [x] **Node.js**: It's not nodejs, node, and other variants.

### CODE REVIEW

**Review by jmcdo29 — APPROVED** [review]

**Comment by jmcdo29** [comment]
Looks like there are conflicts with rebasing. Could you get those fixed so we can merge this via a rebase?

**Comment by Innei** [comment]
> Looks like there are conflicts with rebasing. Could you get those fixed so we can merge this via a rebase?

`This branch has no conflicts with the base branch`, it can not merge now?

**Comment by jmcdo29** [comment]
> there are conflicts with rebasing

image

**Review by micalevisk — APPROVED** [review]

**Comment by Innei** [comment]
> > there are conflicts with rebasing
> 
> image

OK, I rebased it.

**Pull request merged**
