### PR TITLE
add nest-transact package

### PR DESCRIPTION
**Pull request by alphamikle**

### CODE REVIEW

**Comment by alphamikle** [comment]
Hello, @juliandavidmr! Currently, now my package has more than 10 stars (21). Can it be acceptable to the repo?

**Comment by alphamikle** [comment]
@juliandavidmr @joebowbeer @automata @evereq
Hello, everyone! Maybe someone can accept this MR? For now, [nest-transact](https://github.com/alphamikle/nest_transact) have 43 stars

**Comment by jmcdo29** [comment]
If you can resolve the nerve conflicts, we can get this merged

**Comment by alphamikle** [comment]
@jmcdo29 Unfortunately - I deleted the old repo with the original pull-request's commit and created the new [PR](https://github.com/nestjs/awesome-nestjs/pull/183)

**Pull request closed without merging**
