### PR TITLE
docs(): improvements

### PR DESCRIPTION
**Pull request by Tony133**
In this PR I have done the following things:

- removed `.yo-rc.json`, as we didn't use Yeoman scaffolding and `travis.yml` for nodejs is not needed since it's a README. (useless files)

- Renamed `code-of-conduct.md` to `CODE_OF_CONDUCT.md`

- Renamed `contributing.md` in `CONTRIBUTING.md`

- Updated the README with the renaming of some links and added a subtitle to the `README.md`

P.s. NestJS ❤️ 😻 👀

### CODE REVIEW

**Review by jmcdo29 — COMMENTED** [review]
LGTM. Are these the rest of the changes you see needing to be made at the moment? Just trying to lump them all into a single PR to have a one and done from here

**Comment by Tony133** [comment]
I made a commit which removes the `package.json`

**Comment by Tony133** [comment]
I added a testing category (see issue [here](https://github.com/nestjs/awesome-nestjs/issues/158))

**Comment by Tony133** [comment]
if everything is ok 🤞, this PR can be merged

**Review by jmcdo29 — APPROVED** [review]

**Pull request merged**
